xcopy /y .\lang\* .\x64\Debug\lang\
xcopy /y .\lang\* .\x64\Release\lang\
xcopy /y .\fonts\* .\x64\Debug\fonts\
xcopy /y .\fonts\* .\x64\Release\fonts\
xcopy /y .\src\shaders\* .\x64\Debug\shaders\
xcopy /y .\src\shaders\* .\x64\Release\shaders\
xcopy /y .\textures\* .\x64\Debug\textures\
xcopy /y .\textures\* .\x64\Release\textures\
xcopy /y .\lib\freetype\*.dll .\x64\Debug\
xcopy /y .\lib\freetype\*.dll .\x64\Release\
xcopy /y .\postpro\*.py .\x64\Debug\postpro\
xcopy /y .\postpro\*.py .\x64\Release\postpro\
xcopy /y .\script\*.py .\x64\Debug\script\
xcopy /y .\script\*.py .\x64\Release\script\